In [3]:
#importando os pacotes a serem utilizados
import pandas as pd
import numpy as np

In [4]:
# Importar os arquivos com as músicas e ver as primeiras linhas
musicas = pd.read_csv("dadosspotify/Music Info.csv", low_memory=False)
musicas.head(3)

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4

In [5]:
# Importar o arquivo de quantidade de reproduções por usuário e ver as primeiras linhas
reproducoes = pd.read_csv("dadosspotify/User Listening History.csv", low_memory=False)
reproducoes.head(3)

             track_id                                   user_id  playcount
0  TRIRLYL128F42539D1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
1  TRFUPBA128F934F7E1  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1
2  TRLQPQJ128F42AA94F  b80344d063b5ccb3212f76538f3d9e43d87dca9e          1

In [6]:
# Filtrando somente as colunas necessárias
# Seleciona somente as variaveis que iremos utilizar
musicas = musicas[["track_id", "name", "artist", "year"]]
musicas.rename (columns = {"track_id":"id_musica", "name":"nome_musica", "artist":"artista", "year":"ano"}, inplace = True)
musicas.head()

            id_musica      nome_musica          artista   ano
0  TRIOREW128F424EAF0   Mr. Brightside      The Killers  2004
1  TRRIVDJ128F429B0E8       Wonderwall            Oasis  2006
2  TROUVHL128F426C441  Come as You Are          Nirvana  1991
3  TRUEIND128F93038C4      Take Me Out  Franz Ferdinand  2004
4  TRLNZBD128F935E4D8            Creep        Radiohead  2008

In [7]:
# Filtrando somente as colunas necessárias
# Seleciona somente as variaveis que iremos utilizar
reproducoes.rename(columns={"track_id":"id_musica", "user_id":"id_usuario", "playcount":"qtd_reproducoes"}, inplace=True)
reproducoes.head()

,id_musica,id_usuario,qtd_reproducoes
0,TRIRLYL128F42539D1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
1,TRFUPBA128F934F7E1,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
2,TRLQPQJ128F42AA94F,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
3,TRTUCUY128F92E1D24,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1
4,TRHDDQG12903CB53EE,b80344d063b5ccb3212f76538f3d9e43d87dca9e,1

In [8]:
# Verificando a existência de valores nulos, não tem então não tem tratamento
musicas.isna().sum()

id_musica      0
nome_musica    0
artista        0
ano            0
dtype: int64

In [9]:
# Verificando a existência de valores nulos, não tem então não tem tratamento
reproducoes.isna().sum()

id_musica          0
id_usuario         0
qtd_reproducoes    0
dtype: int64

In [10]:
# Quantas vezes cada usuário aparece
reproducoes['id_usuario'].value_counts()

id_usuario
ec6dfcf19485cb011e0b22637075037aae34cf26    784
4e11f45d732f4861772b2906f81a7d384552ad12    384
726da71c2c2ea119119a7957517fccd028d1be76    376
113255a012b2affeab62607563d03fbdf31b08e7    367
7adec7f006cb09482d36609d205293d8b61f030e    366
                                           ...
03fc1edc907164fa07bf45378e5fd088b2a7433f      1
015fccf4b6908eec2f0710fa19ebd64f3e1b0feb      1
d7a8b4f8b04f6512868a124b65eab759d124d1af      1
b5ac16eeb8d174707e2e4230e3a6b0f63caaac47      1
a4b757e7691f803a8d28f5eceeeb8c2826b20d97      1
Name: count, Length: 962037, dtype: int64

In [11]:
# Cria um filtro para utilizarmos apenas usuarios que escutaram mais de 80 músicas
qt_reproducao = reproducoes['id_usuario'].value_counts() > 80
y = qt_reproducao[qt_reproducao].index
y.shape

(6884,)

In [12]:
print(y)
reproducoes.shape

Index(['ec6dfcf19485cb011e0b22637075037aae34cf26',
       '4e11f45d732f4861772b2906f81a7d384552ad12',
       '726da71c2c2ea119119a7957517fccd028d1be76',
       '113255a012b2affeab62607563d03fbdf31b08e7',
       '7adec7f006cb09482d36609d205293d8b61f030e',
       'fef771ab021c200187a419f5e55311390f850a50',
       '8cb51abc6bf8ea29341cb070fe1e1af5e4c3ffcc',
       'b4c94d72b15d3c311c10045a58b31f95d9d12785',
       '96f7b4f800cafef33eae71a6bc44f7139f63cd7a',
       '6d625c6557df84b60d90426c0116138b617b9449',
       ...
       '8a40932a74b6c4b37c6b2e3c3d66e8bfd690d36b',
       '7f7733e6659661dfd299aa9b70fe0873e9563467',
       '55536d5217f9c48c0b4abe2b9b4482e3b4be7640',
       'dab93b3958b74765406a8ddcd3400e17cc85ebeb',
       'ed6d7950b4a5aff67f51534939fff051b9cf89e3',
       'be05d51ab1aad0af88dda688a1ec7b0467f2c0a4',
       '8d4421cf687538e69561c0a1b6d758d7b4acc41d',
       '5595f7ef3b2a413399dc7682175a09d2a2bfc393',
       '458f60aaa192d29b92f071c3379633d93f85f761',
       '61457d4f6b5053031c358de46929960f3d32d782'],
      dtype='str', name='id_usuario', length=6884)

(9711301, 3)

In [13]:
# Filtro para atualizar o dataframe apenas com o que satisfazem a condição
reproducoes = reproducoes[reproducoes["id_usuario"].isin(y)]
reproducoes.shape

(772668, 3)

In [14]:
# Mostra os tipos das variáveis do dataframe
musicas.info()
reproducoes.info()
# as colunas estão com mesmo tipo, então não precisa de tratamento

<class 'pandas.DataFrame'>
RangeIndex: 50683 entries, 0 to 50682
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_musica    50683 non-null  str
 1   nome_musica  50683 non-null  str
 2   artista      50683 non-null  str
 3   ano          50683 non-null  int64
dtypes: int64(1), str(3)
memory usage: 1.5 MB
<class 'pandas.DataFrame'>
Index: 772668 entries, 121 to 9711012
Data columns (total 3 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id_musica        772668 non-null  str
 1   id_usuario       772668 non-null  str
 2   qtd_reproducoes  772668 non-null  int64
dtypes: int64(1), str(2)
memory usage: 23.6 MB

In [15]:
reproducoes_e_musica = reproducoes.merge(musicas, on = "id_musica")
reproducoes_e_musica.head()

,id_musica,id_usuario,qtd_reproducoes,nome_musica,artista,ano
0,TRLATHU128F92FC275,5a905f000fc1ff3df7ca807d57edb608863db05d,11,Freedom Blade,This Will Destroy You,2009
1,TRMKFPN128F42858C3,5a905f000fc1ff3df7ca807d57edb608863db05d,2,Caterpillar House,Black Moth Super Rainbow,2006
2,TRTSSUT128F1472A51,5a905f000fc1ff3df7ca807d57edb608863db05d,1,Tchaparian,Hot Chip,2006
3,TRNJLKP128F427CE28,5a905f000fc1ff3df7ca807d57edb608863db05d,1,Aerodynamic,Daft Punk,2001
4,TRGAOLV128E0789D40,5a905f000fc1ff3df7ca807d57edb608863db05d,2,Swallowed in the Sea,Coldplay,2005

In [14]:
reproducoes_e_musica.shape

(772668, 6)

In [16]:
# Apagar duplicados de mesmo usuário para a mesma música
reproducoes_e_musica.drop_duplicates(["id_musica", "id_usuario"], inplace = True)
reproducoes_e_musica.shape

(772668, 6)

In [17]:
# Apagar a variável id_filme pois não será utilizada
del reproducoes_e_musica['id_musica']
reproducoes_e_musica.head()

,id_usuario,qtd_reproducoes,nome_musica,artista,ano
0,5a905f000fc1ff3df7ca807d57edb608863db05d,11,Freedom Blade,This Will Destroy You,2009
1,5a905f000fc1ff3df7ca807d57edb608863db05d,2,Caterpillar House,Black Moth Super Rainbow,2006
2,5a905f000fc1ff3df7ca807d57edb608863db05d,1,Tchaparian,Hot Chip,2006
3,5a905f000fc1ff3df7ca807d57edb608863db05d,1,Aerodynamic,Daft Punk,2001
4,5a905f000fc1ff3df7ca807d57edb608863db05d,2,Swallowed in the Sea,Coldplay,2005

In [18]:
# Quero que cada id_usuario seja uma variavel com o respectivo valor de nota 
# para cada filme avaliado
musicas_pivot = reproducoes_e_musica.pivot_table(columns = "id_usuario", index = "nome_musica", values = "qtd_reproducoes")
musicas_pivot.head(20)

id_usuario,000d80cd9b58a8f77b33aa613dcfc5cbf1daf5e8,001889ee41b5f31c404a1abe4af07b2377fa776b,001fd039ab4472039d22f9481bb5c5d376c3032f,0025bfe6248070545d23721083acd3f60451da4f,002b63a7e2247de6d62bc62f253474edc7dd044c,0037cbbc2cd55e2ba6d6839b15175522339aadec,003a74775bf18a5e3b0719de1281f891db0e6f95,003d0f3aac94fd261bb74c0124a90750579972d4,003e65b2927f157f951e940b51b9f91a74991834,003fb2edb9dd18a2a45899e4b33fd1c746aecc23,...,ff75f58dff87e9f9f767134882e515e75cd94dde,ff7fd21f53d31a5f74ec295330f9f2592138067c,ffc0053f56ec6af196bd740e29d465f2985c0246,ffc1b96de28a52f8161cb1a3a119222c319ece93,ffd458f903d49854685cf4540245c1d297e8bafa,ffdaab327f2fc6b9fa01a4e3e7f41fdd0e468046,ffe26e9c5e824a2bd36c04cd56200c316fe79c22,fff03efd1550136063389fa71125194614e1c68f,fff6c30c773e6ffafcac213c9afd9666afaf6d63,fffb0b218640d86e5cb99d41cd3ecad977142da5
nome_musica,,,,,,,,,,,,,,,,,,,,,
#1 Zero,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$20 for Boban,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$29.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
& Down,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'97 Bonnie & Clyde,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(*Fin),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(A Shimmering Radiance) Diadem of 12 Stars,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Antichrist Television Blues),NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN
(Big) John Wayne Socks Psychology On The Jaw,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Do)Minion,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Don't Fear) The Reaper,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Drawing) Rings Around The World,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Début),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Far From) Home,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Go To) California,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# Substitui os valores nulos por 0
musicas_pivot.fillna(0, inplace = True)
musicas_pivot.head(20)

id_usuario,000d80cd9b58a8f77b33aa613dcfc5cbf1daf5e8,001889ee41b5f31c404a1abe4af07b2377fa776b,001fd039ab4472039d22f9481bb5c5d376c3032f,0025bfe6248070545d23721083acd3f60451da4f,002b63a7e2247de6d62bc62f253474edc7dd044c,0037cbbc2cd55e2ba6d6839b15175522339aadec,003a74775bf18a5e3b0719de1281f891db0e6f95,003d0f3aac94fd261bb74c0124a90750579972d4,003e65b2927f157f951e940b51b9f91a74991834,003fb2edb9dd18a2a45899e4b33fd1c746aecc23,...,ff75f58dff87e9f9f767134882e515e75cd94dde,ff7fd21f53d31a5f74ec295330f9f2592138067c,ffc0053f56ec6af196bd740e29d465f2985c0246,ffc1b96de28a52f8161cb1a3a119222c319ece93,ffd458f903d49854685cf4540245c1d297e8bafa,ffdaab327f2fc6b9fa01a4e3e7f41fdd0e468046,ffe26e9c5e824a2bd36c04cd56200c316fe79c22,fff03efd1550136063389fa71125194614e1c68f,fff6c30c773e6ffafcac213c9afd9666afaf6d63,fffb0b218640d86e5cb99d41cd3ecad977142da5
nome_musica,,,,,,,,,,,,,,,,,,,,,
#1 Zero,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
#24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$20 for Boban,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$29.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
$300,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
& Down,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
'97 Bonnie & Clyde,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(*Fin),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(A Shimmering Radiance) Diadem of 12 Stars,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Antichrist Television Blues),0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0
(Big) John Wayne Socks Psychology On The Jaw,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Do)Minion,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Don't Fear) The Reaper,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Drawing) Rings Around The World,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Début),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Far From) Home,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
(Go To) California,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [20]:
#importar csr_matriz do pacote SciPy
#possibilita a criação de matrizes sparsas
from scipy.sparse import csr_matrix

#Transformar o dataset em uma matriz sparsa
musicas_sparse = csr_matrix(musicas_pivot)

In [21]:
type(musicas_sparse)

scipy.sparse._csr.csr_matrix

In [22]:
#Importar o algoritmo KNN que calcula com base na distância
#do pacote SciKit Learn
from sklearn.neighbors import NearestNeighbors

In [23]:
#Criando e treinando modelo preditivo
modelo = NearestNeighbors(algorithm="brute")
modelo.fit(musicas_sparse)

NearestNeighbors(algorithm='brute')

Vamos fazer previsões e sugestões de músicas

In [24]:
#Wonderwall
distances, sugestions = modelo.kneighbors(musicas_pivot.filter(items = ["Wonderwall"], axis=0).values.reshape(1, -1))

for i in range(len(sugestions)):
    print(musicas_pivot.index[sugestions[i]])

Index(['Wonderwall', 'Candy Says', 'Pills', 'Cat People (Putting Out Fire)',
       'Another Woman'],
      dtype='str', name='nome_musica')